# Generated by Django 2.2.12 on 2020-05-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_characterindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='type',
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
    ]
