# Generated by Django 2.2.12 on 2020-05-31 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_characterpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterpage',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Character'),
        ),
    ]
