# Generated by Django 2.2.12 on 2020-06-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20200601_1016'),
        ('character', '0007_auto_20200531_1451'),
    ]

    operations = [
    ]
