name: Tests

on:
  push:

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: miami

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install flake8 coverage
          pip install -r requirements.txt
      - name: Run tests
        run: |
          bash test.sh
          ls
      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
